exclude: ['Rakefile', 'Procfile', 'README.md', 'config.rb', 'Gemfile', 'Gemfile.lock', '_settings.yml']
gems: ['bourbon', 'susy', 'jekyll-feed', 'jekyll-sitemap']

title: Digital Humanities
email: digitalhumanities@virginia.edu

sass:
  sass_dir: _sass
  style: compressed

collections:
  centers:
    output: true
    permalink: /centers/:path/
  collaborators:
    output: true
    permalink: /collaborators/:path/
  projects:
    output: true
    permalink: /projects/:path/
